### PR TITLE
New endpoint

### PR DESCRIPTION
**Pull request by stefansundin**
I was wondering why your feed stopped working. Here's a fix.

### CODE REVIEW

**Comment by tedder** [comment]
Oh, nice. And I like your bucket-map so it can be usable outside of my world. Gonna merge and test locally.

**Comment by tedder** [comment]
Works perfectly- "deployed" it, so it'll go back to updating every 6 hours. Ping me if you ever see any weirdness!

**Comment by stefansundin** [comment]
Great! Thanks for merging it so quickly. :)

**Comment by stefansundin** [comment]
I guess an even better (maybe faster?) way of checking if you are you, would be to use the head_bucket API call..

```
aws s3api head-bucket --bucket tedder
```

Oh well, both work.

**Comment by tedder** [comment]
Eh, I don't care too much. 4 calls to ListBuckets per day isn't bad. The other other way to do it is to add a flag for DEV_MODE.

**Pull request merged**
